# Generated by Django 2.2.6 on 2019-10-21 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(default='', max_length=20, verbose_name='Singer name')),
                ('age', models.PositiveIntegerField(default='', verbose_name='singer age')),
                ('sex', models.CharField(default='', max_length=20, verbose_name='sex of singer')),
                ('number', models.CharField(default='', max_length=20, verbose_name='number of singer')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='Name of Groups')),
                ('style', models.CharField(default='', max_length=20, verbose_name='style of group')),
                ('date', models.DateField(default='', max_length=20, verbose_name='date of realize')),
                ('count', models.ManyToManyField(to='million.Singer')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='', max_length=20, verbose_name='date of concert')),
                ('place', models.CharField(default='', max_length=20, verbose_name='place of concert')),
                ('group_concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='million.Groups')),
            ],
        ),
    ]
