# Generated by Django 2.2.6 on 2019-11-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.PositiveIntegerField(default='', verbose_name='orderid')),
                ('date', models.DateField(default='', max_length=20, verbose_name='date')),
                ('servicefee', models.PositiveIntegerField(default='', verbose_name='servicefee')),
                ('totalsum', models.PositiveIntegerField(default='', verbose_name='totalsum')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Meal_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='place of concert')),
                ('departmentid', models.ManyToManyField(to='million.Departments')),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='name')),
                ('price', models.PositiveIntegerField(default='', verbose_name='price')),
                ('description', models.CharField(default='', max_length=20, verbose_name='description')),
                ('categoryid', models.ManyToManyField(to='million.Meal_Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Meals_to_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.PositiveIntegerField(default='', verbose_name='orderd')),
                ('meals', models.ManyToManyField(to='million.Meals')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableid', models.PositiveIntegerField(default='', verbose_name='tableid')),
                ('meals', models.ManyToManyField(to='million.Meals')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default='', verbose_name='percentage')),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='name')),
                ('surname', models.CharField(default='', max_length=20, verbose_name='surname')),
                ('email', models.CharField(default='', max_length=20, verbose_name='email')),
                ('roleid', models.PositiveIntegerField(default='', verbose_name='roleid')),
                ('phone', models.PositiveIntegerField(default='', verbose_name='phone')),
            ],
        ),
        migrations.RemoveField(
            model_name='groups',
            name='count',
        ),
        migrations.RemoveField(
            model_name='singer',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Concert',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Singer',
        ),
        migrations.AddField(
            model_name='checks',
            name='meals',
            field=models.ManyToManyField(to='million.Meals'),
        ),
    ]
