# Generated by Django 2.2.6 on 2019-11-24 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0002_auto_20191124_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checks',
            name='orderid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='million.Orders'),
        ),
        migrations.RemoveField(
            model_name='meal_categories',
            name='departmentid',
        ),
        migrations.AddField(
            model_name='meal_categories',
            name='departmentid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='million.Departments'),
        ),
        migrations.RemoveField(
            model_name='meals',
            name='categoryid',
        ),
        migrations.AddField(
            model_name='meals',
            name='categoryid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='million.Meal_Categories'),
        ),
        migrations.AlterField(
            model_name='meals_to_order',
            name='orderid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='million.Orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tableid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='million.Table'),
        ),
        migrations.AlterField(
            model_name='users',
            name='roleid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='million.Roles'),
        ),
    ]
