# Generated by Django 2.2.6 on 2019-12-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0003_auto_20191124_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals_to_order',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='meals_to_order',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='tableid',
        ),
        migrations.AddField(
            model_name='users',
            name='dateofadd',
            field=models.DateField(default='', max_length=20, verbose_name='dateofadd'),
        ),
        migrations.AlterField(
            model_name='meal_categories',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='Checks',
        ),
        migrations.DeleteModel(
            name='Meals_to_order',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
