# Generated by Django 2.2.6 on 2019-12-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0004_auto_20191203_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='dateofadd',
        ),
        migrations.AddField(
            model_name='users',
            name='date',
            field=models.DateField(default='', max_length=20, verbose_name='dateofadd'),
        ),
    ]
