# Generated by Django 2.2.6 on 2019-12-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('million', '0005_auto_20191203_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='login',
            field=models.CharField(default='', max_length=20, verbose_name='login'),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=20, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='servicepercentage',
            name='percentage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='million.Statuses'),
        ),
    ]
